// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIA8yMXEVFr8RqH6fLe_cOkbj3umgNpk',
    appId: '1:419559532657:web:b8ac0dff535a1101b213d0',
    messagingSenderId: '419559532657',
    projectId: 'wireless-build-tool',
    authDomain: 'wireless-build-tool.firebaseapp.com',
    storageBucket: 'wireless-build-tool.appspot.com',
    measurementId: 'G-T09HJV8700',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwYmTpyDeQSUHUB2RrH7INUm_wcaGxHVI',
    appId: '1:419559532657:android:e68c1d21a6e47de3b213d0',
    messagingSenderId: '419559532657',
    projectId: 'wireless-build-tool',
    storageBucket: 'wireless-build-tool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWToWVrl5Iiqpe4bh6M4TtjV6pMh30aFM',
    appId: '1:419559532657:ios:e5e2e7a9d985ac8cb213d0',
    messagingSenderId: '419559532657',
    projectId: 'wireless-build-tool',
    storageBucket: 'wireless-build-tool.appspot.com',
    iosClientId: '419559532657-gm9m3hqb4suo7boo26qsgpci1lmleqvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.wirelessBuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWToWVrl5Iiqpe4bh6M4TtjV6pMh30aFM',
    appId: '1:419559532657:ios:e5e2e7a9d985ac8cb213d0',
    messagingSenderId: '419559532657',
    projectId: 'wireless-build-tool',
    storageBucket: 'wireless-build-tool.appspot.com',
    iosClientId: '419559532657-gm9m3hqb4suo7boo26qsgpci1lmleqvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.wirelessBuild',
  );
}
